services:
  mysql:
    image: mysql:8.0
    container_name: carminepf-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: carminepf
      MYSQL_USER: carminepf
      MYSQL_PASSWORD: carminepf123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - carminepf-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: carminepf-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://carminepf:carminepf123@mysql:3306/carminepf
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - mysql
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    networks:
      - carminepf-network
    command: npm run start:prod

volumes:
  mysql_data:

networks:
  carminepf-network:
    driver: bridge